name: Build & Push Docker Containers

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: |
          pwd
          echo "Change directory"
          cd Server
          echo "Start restoring dependencies"
          dotnet restore
      - name: Build
        run: |
          pwd
          echo "Change directory"
          cd Server
          echo "Start building"
          dotnet build --no-restore
      - name: Test
        run: |
          pwd
          echo "Change directory"
          cd Server
          echo "Start running tests"
          dotnet test --no-build --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          cd Server
          ls
          echo "LOG: build and push redirect service"
          docker build --build-arg MESSAGING_HOST="${{ secrets.MESSAGING_HOST }}" --build-arg MESSAGING_ACCESS_KEY="${{ secrets.MESSAGING_ACCESS_KEY }}" --build-arg MESSAGING_SECRET_KEY="${{ secrets.MESSAGING_SECRET_KEY }}" --build-arg CONNECTION_STRING="${{ secrets.REDIRECT_CONNECTION_STRING }}" --build-arg JWT_ISS="${{ secrets.JWT_ISS }}" --build-arg JWT_AUD="${{ secrets.JWT_AUD }}" --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" -t salex2202/splitify:redirect-latest -f src/Services/Redirect/Splitify.Redirect.Api/Dockerfile . --push
          echo "LOG: build and push campaign service"
          docker build --build-arg MESSAGING_HOST="${{ secrets.MESSAGING_HOST }}" --build-arg MESSAGING_ACCESS_KEY="${{ secrets.MESSAGING_ACCESS_KEY }}" --build-arg MESSAGING_SECRET_KEY="${{ secrets.MESSAGING_SECRET_KEY }}" --build-arg CONNECTION_STRING="${{ secrets.CAMPAIGN_CONNECTION_STRING }}" --build-arg JWT_ISS="${{ secrets.JWT_ISS }}" --build-arg JWT_AUD="${{ secrets.JWT_AUD }}" --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" -t salex2202/splitify:campaign-latest -f src/Services/Campaign/Splitify.Campaign.Api/Dockerfile . --push
          echo "LOG: build and push identity service"
          docker build --build-arg RESET_PASSWORD_URL="${{ secrets.RESET_PASSWORD_URL }}" --build-arg MESSAGING_HOST="${{ secrets.MESSAGING_HOST }}" --build-arg MESSAGING_ACCESS_KEY="${{ secrets.MESSAGING_ACCESS_KEY }}" --build-arg MESSAGING_SECRET_KEY="${{ secrets.MESSAGING_SECRET_KEY }}" --build-arg CONNECTION_STRING="${{ secrets.IDENTITY_CONNECTION_STRING }}" --build-arg JWT_ISS="${{ secrets.JWT_ISS }}" --build-arg JWT_AUD="${{ secrets.JWT_AUD }}" --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" -t salex2202/splitify:identity-latest -f src/Services/Identity/Splitify.Identity.Api/Dockerfile . --push
          echo "LOG: build and push email sender"
          docker build --build-arg MESSAGING_HOST="${{ secrets.MESSAGING_HOST }}" --build-arg MESSAGING_ACCESS_KEY="${{ secrets.MESSAGING_ACCESS_KEY }}" --build-arg MESSAGING_SECRET_KEY="${{ secrets.MESSAGING_SECRET_KEY }}" --build-arg SMTP_API_PATH="${{ secrets.SMTP_API_PATH }}" --build-arg SMTP_API_KEY="${{ secrets.SMTP_API_KEY }}" --build-arg SMTP_SENDER_EMAIL="${{ secrets.SMTP_SENDER_EMAIL }}" --build-arg SMTP_SENDER_NAME="${{ secrets.SMTP_SENDER_NAME }}" -t salex2202/splitify:emailsender-latest -f src/Apps/Splitify.EmailSender/Dockerfile . --push
          
        env:
          DOCKER_BUILDKIT: 1
