name: publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: |
          pwd
          echo "Change directory"
          cd Server
          echo "Start restoring dependencies"
          dotnet restore
      - name: Build
        run: |
          pwd
          echo "Change directory"
          cd Server
          echo "Start building"
          dotnet build --no-restore
      - name: Test
        run: |
          pwd
          echo "Change directory"
          cd Server
          echo "Start running tests"
          dotnet test --no-build --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Services
        run: |
          cd Server
          
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker buildx build -t salex2202/splitify:redirect-latest -f src/Services/Redirect/Splitify.Redirect.Api/Dockerfile .
          docker buildx build -t salex2202/splitify:campaign-latest -f src/Services/Campaign/Splitify.Campaign.Api/Dockerfile .
          docker buildx build -t salex2202/splitify:identity-latest -f src/Services/Identity/Identity.Campaign.Api/Dockerfile .
          docker buildx build -t salex2202/splitify:emailsender-latest -f src/Apps/Splitify.EmailSender/Dockerfile .

          docker push salex2202/splitify:redirect-latest
          docker push salex2202/splitify:campaign-latest
          docker push salex2202/splitify:identity-latest
          docker push salex2202/splitify:emailsender-latest

        env:
          DOCKER_BUILDKIT: 1
